lib/utils/to_readable_number.dart
=> to_readable_number.dartの.0を削除

lib/widgets/container/modal/feed_action_modal_container.dart
=> FeedActionModalContainerのDividerの位置を移動

lib/screens/login_screen.dart
=> パスワード表示/非表示ボタンを追加

lib/widgets/button/follow_button.dart, lib/widgets/dialog/unfollow_dialog.dart, lib/widgets/list_tile/feed_work_list_tile.dart
=> FeedWorkListTileにフォローボタンとシェアボタンを追加

lib/screens/explorer/explorer_screen.dart, lib/widgets/app_bar/search_app_bar.dart
=> fix: 検索画面のバツボタンが正しく動作していなかった問題を修正

lib/screens/album/album_screen.dart, lib/screens/folder/folder_screen.dart
=> シリーズやフォルダの中身が空の場合にも、ヘッダーを表示する

lib/providers/interactive_image_dialog_matrix4_provider.dart, lib/providers/interactive_image_dialog_matrix4_provider.g.dart, lib/screens/work/work_screen.dart, lib/widgets/dialog/interactive_image_dialog.dart, lib/widgets/image/feed_image.dart
resolve #78 
haruharu-1105さんの提案してくださった仕様を実装しました。
=> フィード画面と作品画面の画像拡大表示を改善

lib/widgets/list_tile/notification/notification_liked_work_list_tile_compact.dart
fix #81 
簡単なtypoの修正ですが、動作確認できていないので、WIPとさせていただきます。
=> WIP: スマホUIで、いいね通知のユーザー名末尾に_がついてしまう問題を修正

lib/screens/work/work_screen.dart, lib/widgets/container/modal/user_action_modal_container.dart, lib/widgets/container/modal/work_action_modal_container.dart, lib/widgets/container/user_header_action_container.dart, lib/widgets/list_tile/feed_work_list_tile.dart
=> 自分に対してフォロ・ミュート・通報のボタンが押せてしまう問題を修正

lib/screens/work/work_screen_compact.dart, lib/screens/work/work_screen_medium.dart, lib/widgets/container/modal/feed_action_modal_container.dart, lib/widgets/container/modal/user_action_modal_container.dart, lib/widgets/container/notification_user_container.dart, lib/widgets/container/work_user_profile_container.dart
=> ユーザー名が画面に収まりきらない場合、自動的に省略する

lib/screens/album/album_screen.dart, lib/widgets/list_tile/album_work_list_tile.dart, lib/widgets/view/album_works_view.dart
Simulatorでは問題なさそうだったので、iPadで確認したらマージします。
=> WIP: アルバム画面をフィード形式で表示する

lib/widgets/button/feed_like_button.dart
=> fix: フィード画面の作品に別の画面からいいねした際、フィードのいいね状態が実際と異なってしまう問題を修正

lib/router.dart, lib/screens/explorer/explorer_screen.dart, lib/screens/search/search_screen.dart, lib/widgets/app_bar/search_app_bar.dart
=> fix: 「みつける」のヘッダーと内容が一致しなくなることがある問題を修正

lib/widgets/avatar/header_user_profile_avatar.dart, lib/widgets/avatar/user_profile_avatar.dart, lib/widgets/container/notification_image_container_compact.dart, lib/widgets/container/notification_image_container_medium.dart, lib/widgets/container/notification_sticker_comment_container.dart, lib/widgets/image/interactive_work_image.dart, lib/widgets/image/sticker_image.dart, lib/widgets/list_tile/notification/notification_work_comment_list_tile_medium.dart, lib/widgets/list_tile/notification/notification_work_comment_reply_list_tile_medium.dart
=> update: CachedNetworkImageをより多くの場所で利用する

lib/widgets/list_tile/modal_follow_user_list_tile.dart
=> fix: フィード画面内のメニューからフォロー操作を行った場合、非ログイン時でもログインを促すダイアログが表示されない問題を修正

lib/widgets/container/modal/feed_action_modal_container.dart, lib/widgets/container/modal/user_action_modal_container.dart, lib/widgets/container/modal/work_action_modal_container.dart
=> fix: 非ログイン時にミュートボタンを表示しない

lib/widgets/form/login_id_form.dart
=> update: ハイフンを含むIDに対応する

lib/graphql/__generated__/album.ast.gql.dart, lib/graphql/__generated__/album.data.gql.dart, lib/graphql/__generated__/album.data.gql.g.dart, lib/graphql/album.graphql, lib/screens/album/album_screen.dart, lib/utils/to_share_album_text.dart, lib/widgets/container/modal/album_action_modal_container.dart
=> update: シリーズ画面にモーダルを追加

lib/widgets/container/work_comment_form_container.dart
=> update: コメントが未入力またはスタンプが未選択の場合、送信ボタンを押せなくする。

lib/widgets/list_tile/notification/notification_work_award_list_tile.dart, lib/widgets/list_tile/notification/notification_work_award_list_tile_compact.dart, lib/widgets/list_tile/notification/notification_work_award_list_tile_medium.dart
=> fix: 定期いいね通知が正常に表示されない問題を修正

lib/widgets/button/feed_like_button.dart
=> update: FeedLikeButtonに最小幅を設定する

lib/screens/explorer/explorer_hot_tags_view.dart
=> fix: 「見つける」内のタグタブから作品が見られない問題を修正

lib/router.dart, lib/screens/config/config_screen.dart, lib/screens/viewer/viewer_liked_works_screen
=> update: いいねの一覧画面を追加

lib/widgets/list_tile/notification/notification_liked_work_list_tile_compact.dart, lib/widgets/list_tile/notification/notification_liked_work_list_tile_medium.dart, lib/widgets/list_tile/notification/notification_work_comment_list_tile_compact.dart, lib/widgets/list_tile/notification/notification_work_comment_list_tile_medium.dart, lib/widgets/list_tile/notification/notification_work_comment_reply_list_tile_compact.dart, lib/widgets/list_tile/notification/notification_work_comment_reply_list_tile_medium.dart
=> update: 通知からユーザーページに移動する機能を追加

lib/app.dart, lib/enums/layout.dart, lib/providers/config_provider.dart, lib/providers/config_provider.g.dart, lib/repositories/config_repository.dart, lib/screens/config/config_theme_screen.dart, lib/screens/root_screen.dart, lib/screens/work/work_screen.dart, lib/states/config_state.dart, lib/states/config_state.freezed.dart, lib/widgets/list_tile/notification/notification_liked_work_list_tile.dart, lib/widgets/list_tile/notification/notification_liked_works_summary_list_tile.dart, lib/widgets/list_tile/notification/notification_work_award_list_tile.dart, lib/widgets/list_tile/notification/notification_work_comment_list_tile.dart, lib/widgets/list_tile/notification/notification_work_comment_reply_list_tile.dart
=> udpate: スマホ向けUIを選択可能にする

lib/widgets/app_bar/work_bottom_app_bar.dart, lib/widgets/button/feed_like_button.dart, lib/widgets/list_tile/modal_follow_user_list_tile.dart, lib/widgets/view/album_works_view.dart
=> update: ホームのログインタブを使用する

lib/widgets/container/modal/comment_action_modal_container.dart, lib/widgets/container/modal/comment_details_modal_container.dart, lib/widgets/container/modal/comment_modal_container.dart, lib/widgets/container/work_comment_container.dart, lib/widgets/view/work_comment_view.dart
close #104 
おそらく動作するのですが、GraphQL側で`システム内部でエラーが発生しました。`というエラーが発生するため、動作確認できていません。
=> update: コメントの削除機能を実装

lib/features/album/album_report_route.dart, lib/features/folder/folder_report_screen.dart, lib/features/post/comment_report_screen.dart, lib/features/post/work_report_screen.dart, lib/features/report/report_screen.dart, lib/features/sticker/sticker_report_screen.dart, lib/features/user/user_report_screen.dart
とりあえずビルドエラーは解消しましたが、不足している機能等があるので追加していきます。
=> 報告機能をベータ版に合わせて更新する
